# Generated by Django 3.2.7 on 2021-09-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
