# Generated by Django 3.2.7 on 2021-09-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='performance',
            field=models.FloatField(),
        ),
    ]
